baseurl: ""
url: "https://projecthydro.org"

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - Rakefile
 - README.md
 - .bundle
 - vendor
 - setup.md

gems:
 - jekyll-multiple-languages-plugin

# Localization config

languages: ["en", "swe", "fil"]

language_names:
  en:
    short: en
    full: English
  swe:
    short: swe
    full: Swedish
  fil:
    short: fil
    full: Filipino
