baseurl: ""
url: "https://projecthydro.org"

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - Rakefile
 - README.md
 - .bundle
 - vendor
 - setup.md

gems:
 - jekyll-multiple-languages-plugin

# Localization config

languages: ["en", "sv", "fil"]

language_names:
  en:
    short: EN
    full: English
  sv:
    short: SV
    full: Svenska
  fil:
    short: FIL
    full: Filipino
